runtime: custom
env: flex
runtime_config: 
  jdk: openjdk8

handlers:
- url: /.*
  script: this field is required, but ignored

# manual_scaling:
#   instances: 1

automatic_scaling:
  max_num_instances: 5
  min_num_instances: 1

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10